import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Milestone, BookOpen, Trophy, Target, Download, MessageSquare, TrendingUp, Building2, Award } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import axios from 'axios';

interface CareerStage {
  year: string;
  description: string;
}

interface CareerRoadmapData {
  title: string;
  Description: string;
  education_paths: { level: string; description: string }[];
  Skills: string[];
  "Career Progression": string;
  "Market Demand": string;
  Salary: string;
  Certifications: string[];
  "Top Companies": string[];
  ten_year_path: CareerStage[];
}

const CareerRoadmap = () => {
  const { careerPath } = useParams();
  const [roadmap, setRoadmap] = useState<CareerRoadmapData | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const contentRef = React.useRef<HTMLDivElement>(null);
  const user = localStorage.getItem('token');

  useEffect(() => {
    const fetchRoadmap = async () => {
      setLoading(true);
      setError(null);
      try {
        if (careerPath) {
          const config = {
            headers: {
              Authorization: `Bearer ${localStorage.getItem('token')}`,
            },
          };
          const response = await axios.get<any>(`/api/careers/path/${encodeURIComponent(careerPath)}`, config);
          const foundCareer = response.data;
          if (foundCareer) {
            setRoadmap({
              title: foundCareer.title,
              Description: foundCareer.Description,
              education_paths: foundCareer.education_paths || [],
              Skills: foundCareer.Skills || [],
              "Career Progression": String(foundCareer["Career Progression"] || ''),
              "Market Demand": String(foundCareer["Market Demand"] || ''),
              Salary: foundCareer.Salary || '',
              Certifications: foundCareer.Certifications || [],
              "Top Companies": Array.isArray(foundCareer["Top Companies"]) ? foundCareer["Top Companies"] : [],
              ten_year_path: foundCareer.ten_year_path || [],
            });
            console.log('Roadmap data loaded:', foundCareer);
            console.log('Career Progression:', foundCareer["Career Progression"]);
            console.log('Market Demand:', foundCareer["Market Demand"]);
            console.log('Top Companies:', foundCareer["Top Companies"]);
            console.log('Top Companies length:', foundCareer["Top Companies"] ? foundCareer["Top Companies"].length : 0);
          } else {
            setError("Career path not found.");
          }
        }
      } catch (err) {
        console.error("Error fetching roadmap:", err);
        setError("Failed to load career roadmap. Please try again later.");
      } finally {
        setLoading(false);
      }
    };

    if (user) {
      fetchRoadmap();
    } else {
      setLoading(false);
      setRoadmap(null);
      setError("Please log in to view career roadmaps.");
    }
  }, [careerPath, user]);

  const handleDownloadPDF = async () => {
    if (!roadmap) return;

    const pdf = new jsPDF('p', 'mm', 'a4');
    let yPos = 20; // Starting Y position
    const margin = 15; // Left/right margin
    const lineHeight = 7; // Approximate line height for text
    const pageHeight = pdf.internal.pageSize.getHeight();
    const contentWidth = pdf.internal.pageSize.getWidth() - 2 * margin;

    // Get user info from localStorage
    const userInfo = JSON.parse(localStorage.getItem('user') || '{}');
    const userName = userInfo.name || 'User';
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const addPageIfNeeded = (requiredHeight: number) => {
      if (yPos + requiredHeight > pageHeight - margin) {
        pdf.addPage();
        yPos = 20; // Reset Y position for new page
        addPageTitleAndFooter();
      }
    };

    const addPageTitleAndFooter = () => {
      // Add title
      pdf.setFontSize(20);
      pdf.text(`${roadmap.title} Career Roadmap`, pdf.internal.pageSize.getWidth() / 2, 10, { align: 'center' });
      
      // Add user name and date
      pdf.setFontSize(10);
      pdf.text(`Generated for: ${userName}`, margin, 15);
      pdf.text(`Date: ${currentDate}`, pdf.internal.pageSize.getWidth() - margin, 15, { align: 'right' });
      
      // Add footer
      pdf.setFontSize(10);
      pdf.text('Generated by Career Pathfinder AI', pdf.internal.pageSize.getWidth() / 2, pageHeight - 10, { align: 'center' });
      pdf.setFontSize(12); // Reset font size for content
    };

    addPageTitleAndFooter();

    // Add Description
    if (roadmap.Description) {
      addPageIfNeeded(20); // Estimate space for title + content
      pdf.setFontSize(16);
      pdf.text('Description', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      const splitDescription = pdf.splitTextToSize(roadmap.Description, contentWidth);
      pdf.text(splitDescription, margin, yPos);
      yPos += splitDescription.length * lineHeight + 10;
    }

    // Add Education Paths
    if (roadmap.education_paths && roadmap.education_paths.length > 0) {
      addPageIfNeeded(30); // Estimate space for title + some items
      pdf.setFontSize(16);
      pdf.text('Education Paths', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      roadmap.education_paths.forEach(path => {
        const pathText = `${path.level}: ${path.description}`;
        const splitPath = pdf.splitTextToSize(pathText, contentWidth);
        addPageIfNeeded(splitPath.length * lineHeight); // Check before adding each item
        pdf.text(`• ${splitPath[0]}`, margin + 5, yPos); // Add bullet point
        for (let i = 1; i < splitPath.length; i++) {
          pdf.text(splitPath[i], margin + 5, yPos + i * lineHeight);
        }
        yPos += splitPath.length * lineHeight;
      });
      yPos += 10;
    }

    // Add Skills
    if (roadmap.Skills && roadmap.Skills.length > 0) {
      addPageIfNeeded(30); // Estimate space for title + some items
      pdf.setFontSize(16);
      pdf.text('Key Skills', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      const skillsText = roadmap.Skills.join(', ');
      const splitSkills = pdf.splitTextToSize(skillsText, contentWidth);
      addPageIfNeeded(splitSkills.length * lineHeight); 
      pdf.text(splitSkills, margin, yPos);
      yPos += splitSkills.length * lineHeight + 10;
    }

    // Add Career Progression
    if (roadmap["Career Progression"]) {
      addPageIfNeeded(20); 
      pdf.setFontSize(16);
      pdf.text('Career Progression', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      const splitProgression = pdf.splitTextToSize(roadmap["Career Progression"], contentWidth);
      pdf.text(splitProgression, margin, yPos);
      yPos += splitProgression.length * lineHeight + 10;
    }

    // Add Market Demand
    if (roadmap["Market Demand"]) {
      addPageIfNeeded(20); 
      pdf.setFontSize(16);
      pdf.text('Market Demand', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      const splitDemand = pdf.splitTextToSize(roadmap["Market Demand"], contentWidth);
      pdf.text(splitDemand, margin, yPos);
      yPos += splitDemand.length * lineHeight + 10;
    }

    // Add Salary
    if (roadmap.Salary) {
      addPageIfNeeded(20); 
      pdf.setFontSize(16);
      pdf.text('Salary', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      const formattedSalary = roadmap.Salary.replace(/<br\/>/g, '\n').replace(/\$/g, '\$'); // Convert <br/> to \n and escape $ for PDF
      const splitSalary = pdf.splitTextToSize(formattedSalary, contentWidth);
      pdf.text(splitSalary, margin, yPos);
      yPos += splitSalary.length * lineHeight + 10;
    }

    // Add Certifications
    if (roadmap.Certifications && roadmap.Certifications.length > 0) {
      addPageIfNeeded(30); 
      pdf.setFontSize(16);
      pdf.text('Certifications', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      roadmap.Certifications.forEach(cert => {
        addPageIfNeeded(lineHeight); 
        pdf.text(`• ${cert}`, margin + 5, yPos);
        yPos += lineHeight;
      });
      yPos += 10;
    }

    // Add Top Companies
    if (roadmap["Top Companies"] && roadmap["Top Companies"].length > 0) {
      addPageIfNeeded(30); 
      pdf.setFontSize(16);
      pdf.text('Top Companies', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      roadmap["Top Companies"].forEach(company => {
        addPageIfNeeded(lineHeight); 
        pdf.text(`• ${company}`, margin + 5, yPos);
        yPos += lineHeight;
      });
      yPos += 10;
    }

    // Add 10-Year Path
    if (roadmap.ten_year_path && roadmap.ten_year_path.length > 0) {
      addPageIfNeeded(30); 
      pdf.setFontSize(16);
      pdf.text('10-Year Path', margin, yPos);
      yPos += 8;
      pdf.setFontSize(12);
      roadmap.ten_year_path.forEach(stage => {
        const stageTitle = `Year ${stage.year}`;
        const stageDescription = stage.description;
        addPageIfNeeded(2 * lineHeight + pdf.splitTextToSize(stageDescription, contentWidth).length * lineHeight); 

        pdf.setFontSize(14); // Slightly larger for stage titles
        pdf.text(stageTitle, margin + 5, yPos);
        yPos += lineHeight;
        pdf.setFontSize(12);
        const splitStageDescription = pdf.splitTextToSize(stageDescription, contentWidth);
        pdf.text(splitStageDescription, margin + 10, yPos);
        yPos += splitStageDescription.length * lineHeight + 5;
      });
      yPos += 10;
    }

    pdf.save(`${roadmap.title.toLowerCase().replace(/\s+/g, '-')}-career-roadmap.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen pt-16 pb-12 flex flex-col items-center">
        <h1 className="text-2xl font-bold text-gray-900">Loading career roadmap...</h1>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen pt-16 pb-12 flex flex-col items-center">
        <h1 className="text-2xl font-bold text-red-500">Error: {error}</h1>
      </div>
    );
  }

  if (!roadmap) {
    return (
      <div className="min-h-screen pt-16 pb-12 flex flex-col items-center">
        <h1 className="text-2xl font-bold text-gray-900">Career path not found.</h1>
      </div>
    );
  }

  return (
    <div className="min-h-screen pt-16 pb-12 bg-gradient-to-br from-indigo-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header Section */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-8 border border-indigo-100">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-4xl font-bold text-indigo-900 mb-3">{roadmap.title} Career Path</h1>
              <p className="text-lg text-gray-600 leading-relaxed">{roadmap.Description}</p>
            </div>
            <div className="flex items-center space-x-4">
              <Link
                to="/feedback"
                className="inline-flex items-center px-4 py-2 border border-indigo-300 text-sm font-medium rounded-lg text-indigo-700 bg-indigo-50 hover:bg-indigo-100 transition-colors duration-200"
              >
                <MessageSquare className="h-5 w-5 mr-2" />
                Give Feedback
              </Link>
              <button
                onClick={handleDownloadPDF}
                className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-lg text-white bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 shadow-md transition-all duration-200 transform hover:scale-105"
              >
                <Download className="h-5 w-5 mr-2" />
                Download Report
              </button>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left Column */}
          <div className="space-y-8">
            {/* Education Paths */}
            {roadmap.education_paths && roadmap.education_paths.length > 0 && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-blue-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-blue-700 mb-4 flex items-center">
                  <BookOpen className="h-6 w-6 mr-2" />
                  Education Paths
                </h2>
                <div className="space-y-4">
                  {roadmap.education_paths.map((path, index) => (
                    <div key={index} className="bg-blue-50 rounded-lg p-4 border border-blue-200">
                      <h3 className="font-semibold text-blue-800 mb-2">{path.level}</h3>
                      <p className="text-gray-700">{path.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Skills Section */}
            {roadmap.Skills && roadmap.Skills.length > 0 && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-purple-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-purple-700 mb-4 flex items-center">
                  <Target className="h-6 w-6 mr-2" />
                  Key Skills
                </h2>
                <div className="flex flex-wrap gap-2">
                  {roadmap.Skills.map((skill, index) => (
                    <span
                      key={index}
                      className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-gradient-to-r from-purple-100 to-indigo-100 text-purple-800 border border-purple-200"
                    >
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right Column */}
          <div className="space-y-8">
            {/* Career Progression */}
            {roadmap["Career Progression"] && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-green-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-green-700 mb-4 flex items-center">
                  <Trophy className="h-6 w-6 mr-2" />
                  Career Progression
                </h2>
                <p className="text-gray-700 leading-relaxed">{roadmap["Career Progression"]}</p>
              </div>
            )}

            {/* Market Demand */}
            {roadmap["Market Demand"] && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-yellow-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-yellow-700 mb-4 flex items-center">
                  <TrendingUp className="h-6 w-6 mr-2" />
                  Market Demand
                </h2>
                <p className="text-gray-700 leading-relaxed">{roadmap["Market Demand"]}</p>
              </div>
            )}

            {/* Top Companies */}
            {roadmap["Top Companies"] && roadmap["Top Companies"].length > 0 && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-red-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-red-700 mb-4 flex items-center">
                  <Building2 className="h-6 w-6 mr-2" />
                  Top Companies
                </h2>
                <div className="grid grid-cols-2 gap-3">
                  {roadmap["Top Companies"].map((company, index) => (
                    <div key={index} className="bg-red-50 rounded-lg p-3 border border-red-200">
                      <p className="text-red-800 font-medium">{company}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Certifications */}
            {roadmap.Certifications && (
              <div className="bg-white rounded-2xl shadow-lg p-6 border border-pink-100 hover:shadow-xl transition-shadow duration-200">
                <h2 className="text-2xl font-semibold text-pink-700 mb-4 flex items-center">
                  <Award className="h-6 w-6 mr-2" />
                  Certifications
                </h2>
                {Array.isArray(roadmap.Certifications) ? (
                  <div className="space-y-3">
                    {roadmap.Certifications.map((cert, index) => (
                      <div key={index} className="bg-pink-50 rounded-lg p-3 border border-pink-200">
                        <p className="text-pink-800">{cert}</p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-gray-700 leading-relaxed">{roadmap.Certifications}</p>
                )}
              </div>
            )}
          </div>
        </div>

        {/* 10-Year Path Section */}
        <div className="mt-12">
          <h2 className="text-3xl font-bold text-indigo-900 mb-8 text-center">10-Year Career Path</h2>
          <div className="space-y-6">
            {roadmap.ten_year_path && roadmap.ten_year_path.length > 0 ? (
              roadmap.ten_year_path.map((stage, index) => (
                <div
                  key={stage.year}
                  className="bg-white rounded-2xl shadow-lg overflow-hidden border border-indigo-100 hover:shadow-xl transition-all duration-200 transform hover:-translate-y-1"
                >
                  <div className="p-6">
                    <div className="flex items-center">
                      <div className="flex-shrink-0">
                        <div className="h-14 w-14 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-full flex items-center justify-center text-white">
                          {index === 0 ? (
                            <BookOpen className="h-7 w-7" />
                          ) : index === roadmap.ten_year_path.length - 1 ? (
                            <Trophy className="h-7 w-7" />
                          ) : (
                            <Milestone className="h-7 w-7" />
                          )}
                        </div>
                      </div>
                      <div className="ml-4">
                        <h2 className="text-2xl font-bold text-indigo-900">Year {stage.year}</h2>
                      </div>
                    </div>

                    <div className="mt-6">
                      <p className="text-gray-700 leading-relaxed">{stage.description}</p>
                    </div>
                  </div>
                </div>
              ))
            ) : (
              <div className="bg-white rounded-2xl shadow-lg p-8 text-center border border-indigo-100">
                <p className="text-gray-500 text-lg">No detailed ten-year path available for this career at the moment.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default CareerRoadmap; 