import React from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Brain, Target, Layout, Users, Calculator, BookOpen, Palette, HandHeart, Crown, ArrowLeft } from 'lucide-react';
import { useEffect, useState } from 'react';
import axios from 'axios';

// Remove unused interface as we will get recommendations directly from backend
// interface CareerRecommendation {
//   title: string;
//   description: string;
//   matchScore: number; // This will be calculated dynamically
//   requiredAbilities: string[];
//   recommendedOrientations: string[];
//   salary: string;
//   growth: string;
// }

// Remove unused interface as we will get recommendations directly from backend
// interface UserScores {
//   abilities: Record<string, number>;
//   orientations: Record<string, number>;
// }

// Remove ML model URL as frontend will call backend
// const ML_MODEL_PREDICT_URL = 'http://127.0.0.1:5001/predict'; // Replace with your actual ML model URL

const CareerRecommendations: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();

  // Remove testData state as we don't need to fetch it separately here
  // const [testData, setTestData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [recommendedCareerTitles, setRecommendedCareerTitles] = useState<string[]>([]);
  const [savedCareerTitles, setSavedCareerTitles] = useState<string[]>([]);
  // Remove ML specific loading and error states
  // const [mlLoading, setMlLoading] = useState(false);
  // const [mlError, setMlError] = useState<string | null>(null);

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        // 1. Fetch recommendations from your backend endpoint
        const token = localStorage.getItem('token');
        console.log('Fetching recommendations - Retrieved token:', token);

        if (!token) {
          setError('User not authenticated. Please log in.');
          setLoading(false);
          // navigate('/login'); // Optional: redirect
          return;
        }

        // Call the backend endpoint that generates and saves recommendations
        const backendResponse = await axios.get('/api/careers/recommendations', {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        // The backend now returns an object with recommendedCareers and savedCareers
        const { recommendedCareers, savedCareers } = backendResponse.data as { 
          recommendedCareers: string[] | undefined; 
          savedCareers: string[] | undefined; // Assuming backend returns saved careers as strings
        };

        if (recommendedCareers && Array.isArray(recommendedCareers)) {
          setRecommendedCareerTitles(recommendedCareers);
          if (savedCareers && Array.isArray(savedCareers)) {
            setSavedCareerTitles(savedCareers);
          }
            } else {
          setError('Backend did not return expected recommendations format.');
          console.error('Backend did not return expected format:', backendResponse.data);
             }

        setLoading(false);

      } catch (err) {
        console.error('Error fetching recommendations:', err);
        if (axios.isAxiosError(err) && err.response?.status === 401) {
          setError('Authentication failed. Please log in again.');
          // localStorage.removeItem('token'); // Optional: clear token
          // navigate('/login'); // Optional: redirect
        } else {
          setError('Failed to fetch recommendations.');
        }
        setLoading(false);
      }
    };

    fetchRecommendations();
  }, []); // Empty dependency array means this runs once on mount

  // Debug: Log the predicted titles
  useEffect(() => {
    console.log('Recommended Career Titles:', recommendedCareerTitles);
    console.log('Saved Career Titles:', savedCareerTitles);
  }, [recommendedCareerTitles, savedCareerTitles]);

  // Use a single loading state
  if (loading) {
    return <div className="text-center text-gray-600">Loading career recommendations...</div>;
  }

  // Use a single error state
  if (error) {
    return <div className="text-center text-red-600">Error: {error}</div>;
  }

  if (recommendedCareerTitles.length === 0) {
       return (
           <div className="text-center text-gray-600 text-lg">
             No specific career recommendations generated by the model.
           </div>
        );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center mb-8 mt-8">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back to Results
          </button>
        </div>

        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Career Recommendations
          </h1>
          <p className="text-xl text-gray-600">
            Here are career paths recommended by our model based on your assessment results.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-4">
          {recommendedCareerTitles.map((title, index) => {
            const isSaved = savedCareerTitles.includes(title);

            const handleSaveCareer = async () => {
              if (isSaved) return; // Do nothing if already saved

              try {
                const token = localStorage.getItem('token');
                if (!token) {
                  console.error('User not authenticated. Cannot save career.');
                  // Optionally, prompt the user to log in
                  return;
                }

                await axios.post('/api/careers/save', { careerTitle: title }, {
                  headers: {
                    Authorization: `Bearer ${token}`,
                  },
                });

                // Update the saved careers state on success
                setSavedCareerTitles(prevSavedCareers => [...prevSavedCareers, title]);
                console.log(`Successfully saved career: ${title}`);
                // Optionally, show a success message to the user

              } catch (err) {
                console.error('Error saving career:', err);
                // Optionally, show an error message to the user
              }
            };

            return (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="bg-white rounded-lg shadow-md p-4 border border-gray-200"
            >
              <h3 className="text-lg font-semibold text-gray-800">{title}</h3>
                <Link 
                  to={`/career-roadmap/${encodeURIComponent(title.toLowerCase().replace(/\s+/g, '-'))}`}
                  className="mt-2 inline-flex items-center px-3 py-1 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200"
                >
                  View Career Path
                </Link>
                <button
                  onClick={handleSaveCareer}
                  disabled={isSaved} // Disable button if already saved
                  className={
                    `mt-2 px-4 py-2 text-sm font-semibold rounded-md 
                     ${isSaved 
                       ? 'bg-gray-300 text-gray-600 cursor-not-allowed' 
                       : 'bg-blue-500 text-white hover:bg-blue-600'
                     }`
                  }
                >
                  {isSaved ? 'Saved' : 'Save'}
                </button>
            </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default CareerRecommendations;